# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'Ubuntu-latest'

steps:
  - script: |
      ./docs.sh
      git config --local user.name "Azure Pipelines"
      git config --local user.email "tamh@mypinpad.com"
      git add .
      git commit -m "Publishing GitHub Pages 5  ***NO_CI***"
    displayName: 'Build and commit pages'

  - task: DownloadSecureFile@1
    name: SecurefileDownload
    inputs:
      secureFile: deploy_key_4
    displayName: 'Get the deploy key'

  - script: |
      echo "$(SecurefileDownload.secureFilePath)"
      cat "$(SecurefileDownload.secureFilePath)"
      mkdir ~/.ssh && mv $(SecurefileDownload.secureFilePath) ~/.ssh/id_ed25519_4
      echo "mkdir done"
      sudo chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519_4
      echo ~/.ssh/id_ed25519_4
      cat ~/.ssh/id_ed25519_4
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      sudo git remote set-url --push origin git@github.com:tamh-mpp/tamh-mpp.github.io.git
      echo "set url done"
      git remote -v
      sudo git push origin HEAD:master
      echo "push done"
    displayName: 'Publish GitHub Pages'